{%$query = $tplData.queryInfo.wordNoSyntax%}{%function urlEnc%}{%for $index= 0 to strlen($url)-1%}%{%dechex(ord($url[$index]))%}{%/for%}{%/function%}{%if preg_match("/^title:/i",$query) !=0%}{%$queryEnc = preg_replace("/^title:/i","",$query)%}{%else%}{%$queryEnc = $query%}{%/if%}{%$queryEnc = $queryEnc|escape:'javascript'|escape%}{%$callBack = $tplData.queryInfo.pUrlConfig.x%}{%if $callBack%}{%$callBack|escape:'javascript'|escape%}({%/if%}{
    "feed":{
        "requestUrl": "http://news.baidu.com/n?tn=json&word={%$tplData.queryInfo.wordNoSyntaxEncoded|escape|escape:'javascript'%}&rn={%$tplData.queryInfo.pUrlConfig.rn|escape:'javascript'|escape%}&pn={%$tplData.queryInfo.pageNo|escape:'javascript'|escape%}&cl={%$tplData.queryInfo.pUrlConfig.cl|escape:'javascript'|escape%}",          "updated": "{%$tplData.queryInfo.listTime|escape:'javascript'|escape%}",          "description":{%json_encode("百度新闻全文搜索_`$queryEnc`")%},
        "relateUrl": "http://news.baidu.com",
        "category": {"label": "百度新闻搜索", "value": {%json_encode($queryEnc)%}},
        "author": {
            "name": "Baidu News Search", 
            "url": "http://news.baidu.com"
        },
        "all": {%$tplData.asResult.asDataDispNum|escape:'javascript'|escape%},          "resultnum":{%$tplData.asResult.asResultNum|escape:'javascript'|escape%},          "pn":{%$tplData.queryInfo.pageNo|escape:'javascript'|escape%},          "rn":{%$tplData.queryInfo.pUrlConfig.rn|escape:'javascript'|escape%},          "entry":[{%foreach $tplData.asResult.item as $res%}{                  "title":{%json_encode($res.offsetInfo.title|highlight:2)%},                  "url":{%json_encode($res.offsetInfo.url|domain_advance|encodeURI)%},                  "urlEnc": "{%urlEnc url=$res.offsetInfo.url%}",                  "source":{%json_encode($res.dispData.rtses)%},                  "category": {                      "label": "百度新闻搜索",                      "value":{%json_encode($queryEnc)%}},                  "abs":{%json_encode($res.offsetInfo.summary|highlight:2)%},                  "imgUrl":{%if isset($res.dispData.ThumURL)%}{%json_encode($res.dispData.ThumURL)%}{%else%}""{%/if%},                  "time":{%json_encode($res.dispData.rtset)%},                  "relate": 0,                  "same":{%json_encode($res.dispData.contnum)%},                  "pn":{%json_encode($res@iteration)%}},{%/foreach%}{}          ]      }  }{%if $callBack%}){%/if%}