{%extends 'base.tpl'%} {%block name='content'%}{%$FE_GBVAR.wrapper_prefix%}<div class="op_tvprogram2"><style >
.op_tvprogram2_table {margin-top:3px;font-size:13px}
.op_tvprogram2_icon {border:0}
.op_tvprogram2_dltd div{font-size:13px;margin:5px 10px;}
.op_tvprogram2_programhead {font-size:13px;font-weight:bold;margin-top:5px}
.op_tvprogram2_linkdiv {margin:8px 0}
.op_tvprogram2_linkdiv div{float:left}
.op_tvprogram2_linkdiv span{float:left;margin:0 6px;font-size:13px}
.op_tvprogram2_linkhead {font-size:13px;font-weight:bold}
.op_tvprogram2_programmore {font-size:13px;color:#7577CA}
.op_tvprogram2_program{font-size:13px;height:18px;float:left;margin:3px 0;padding-left:25px;overflow:hidden;width:440px;background:url(http://www.baidu.com/aladdin/img/tvprogram2/video.gif) no-repeat left center}
{%if $tplData.dualmode!=""%}
.op_tvprogram2_program {width:200px;margin-right:30px;}
{%/if%}
.op_tvprogram2_new{color:#C00;font-size:11px;top:-5px;position:relative}
</style>{%fe_fn_title_prefix%}{%fe_fn_title title="{%$tplData.title%}" url="{%$tplData.url%}"%}{%fe_fn_title_suffix title="{%$tplData.title%}" url="{%$tplData.url%}"%}<table class="op_tvprogram2_table" cellspacing=0 cellpadding=0><tr><td>{%if $tplData.icon[0]['iconlink']!=""%}<a href="{%$tplData.icon[0]['iconlink']%}" href="_blank">{%/if%}<img class="op_tvprogram2_icon" src="{%$tplData.icon[0]['iconaddress']%}">{%if $tplData.icon[0]['iconlink']!=""%}</a>{%/if%}</td><td class="op_tvprogram2_dltd">{%$loop_maxcount=count($tplData.dl)%}{%for $op_loop_count=0 to 3%}{%if $op_loop_count<$loop_maxcount%} <div><span>{%$tplData.dl[$op_loop_count]['dt']%}</span><span>{%if $tplData.dl[$op_loop_count]['ddlink']!=""%}<a href="{%$tplData.dl[$op_loop_count]['ddlink']%}" target="_blank">{%/if%}{%$tplData.dl[$op_loop_count]['dd']|highlight:0%}{%if $tplData.dl[$op_loop_count]['ddlink']!=""%}</a>{%/if%}</span></div>{%else%}{%break%}{%/if%}{%/for%}</td></tr></table>{%if $tplData.programhead!=""%}<div class="op_tvprogram2_programhead">{%$tplData.programhead%}</div>{%/if%}<div class="op_tvprogram2_programdiv">{%$loop_maxcount=count($tplData.program)%}{%for $op_loop_count=0 to 5%}{%if $op_loop_count<$loop_maxcount%} <div class="op_tvprogram2_program"><a href="{%$tplData.program[$op_loop_count]['link']%}" target="_blank">{%$tplData.program[$op_loop_count]['content']|highlight:0%}</a>{%if $tplData.program[$op_loop_count]['new']!=""%}<span class="op_tvprogram2_new">新!</span>{%/if%}</div>{%else%}{%break%}{%/if%}{%/for%}<br clear="all"></div>{%if $tplData.moreprogram[0]['content']!=""%}{%if $tplData.moreprogram[0]['url']!=""%}<div><a class="op_tvprogram2_programmore" href="{%$tplData.moreprogram[0]['url']%}" target="_blank">{%$tplData.moreprogram[0]['content']|highlight:0%}</a></div>{%/if%}{%/if%}{%if $tplData.linkhead!=""%}<div class="op_tvprogram2_linkdiv"><div class="op_tvprogram2_linkhead">{%$tplData.linkhead%}</div>{%$loop_maxcount=count($tplData.link)%}{%for $op_loop_count=0 to 5%}{%if $op_loop_count<$loop_maxcount%} <span><a href="{%$tplData.link[$op_loop_count]['linkurl']%}" target="_blank">{%$tplData.link[$op_loop_count]['linkcontent']|highlight:0%}</a></span>{%else%}{%break%}{%/if%}{%/for%}<br clear="all"></div>{%/if%}<div><span style="font-size:13px;color:#008000;">open.baidu.com/</span>{%if $tplData.showlamp!=""%} - <a target="_blank" href="http://open.baidu.com/"  class="op_LAMP" >{%$FE_GBVAR.aladdin_txt%}</a>{%/if%}</div></div>{%$FE_GBVAR.wrapper_suffix%}{%/block%}