{%fis_widget%}<style>.starScore,.starMask{display:inline-block;height:12px;overflow:hidden;font-size:0;background:url("{%$STATIC_DOMAIN_WWW0%}/cache/global/img/score-1.0.png") repeat-x}.starScore{width:75px;background-position:0 -12px}.wenkuType{display:inline-block;margin-right:5px;vertical-align:top;width:16px;height:16px;background:url({%$STATIC_DOMAIN_WWW0%}/cache/global/img/bg-1.0.10.png) no-repeat 0 -544px}.DOCType{background-position:0 -544px}.PDFType{background-position:-32px -544px}.PPTType{background-position:-64px -544px}.XLSType{background-position:-96px -544px}.TXTType{background-position:-128px -544px}</style><table id="{%$resIndex%}" class="result{%if $isSameSize==1%} c-res{%/if%}"  cellpadding="0" cellspacing="0"><tr><td class="f"><h3 class="t">{%$WenkuArchiveType = ['1'=>'DOC','2'=>'PDF','3'=>'PPT','4'=>'XLS','8'=>'TXT']%}<a href="{%get_url originUrl=$res.offsetInfo.urlEncoded encryptionUrl=$res.encryptionUrl%}" target="_blank" data-click="{
			'F':'{%$res.strategyStr[0]%}',
			'F1':'{%$res.strategyStr[1]%}',
			'F2':'{%$res.strategyStr[2]%}',
			'F3':'{%$res.strategyStr[3]%}',
			'T':'{%$serverTime%}',
            'y':'{%$res.identifyStr%}'}">{%if $res.dispData.WenkuMdocType|array_key_exists:$WenkuArchiveType%}<span class="wenkuType {%$WenkuArchiveType[$res.dispData.WenkuMdocType]%}Type"></span>{%/if%}{%$res.offsetInfo.title|limitlen:60|highlight:2%}</a>{%fis_widget_inline%}{%if $isUserLogin == 1 && $isFavoOn == 1%}{%if $res.favoFlag == 1%}<span class="tsuf"><span class="fav fav_add" data-fav="1" data-id="{%$res.favoItemId%}" title="点击取消收藏" onmousedown="return c({'fm':'bfav','url':this.getAttribute('data-url'),'title':this.getAttribute('data-title'),'p1':bds.se.favo.favPos(this),'p2':0,'p3':1,tab:this.getAttribute('data-fav')});"></span></span>{%else%}<span class="tsuf"><span class="fav fav_nor" data-fav="0" data-id="0" title="点击收藏" onmousedown="return c({'fm':'bfav','url':this.getAttribute('data-url'),'title':this.getAttribute('data-title'),'p1':bds.se.favo.favPos(this),'p2':0,'p3':1,tab:this.getAttribute('data-fav')});"></span></span>{%/if%}{%/if%}{%/fis_widget_inline%}</h3><font size="-1"><p style="padding-top:3px;"><span class="m">{%if isset($res.dispData.WenkuValue)%}<span class="starScore"><span class="starMask" style="width:{%round($res.dispData.WenkuValue * 7.5)%}px;"></span></span>&nbsp;评分:{%$res.dispData.WenkuValue/2%}/5&nbsp;{%/if%}{%$res.dispData.WenkuPage%}页</span></p>{%$res.offsetInfo.summary|limitlen:150|highlight:6%}{%if strlen($res.offsetInfo.summary) > 0%}<br>{%/if%}<span class="g">{%if $res.dispData.DispUrl%}{%$res.dispData.DispUrl|url_bold_html%}{%else%}{%$res.offsetInfo.urlDisplay|url_limit:45:true%}{%/if%}{%$res.dispData.WenkuPostTime%}</span>{%if $isOldSnapshootOn%}{%if strlen($res.snapshootKey) > 0%}-<a data-nolog href="{%$cache_domain%}/c?{%$res.snapshootKey%}&user=baidu&fm=sc&query={%$queryUbs%}&qid={%$queryId%}&p1={%$resIndex%}" 
					{%if !($urlPara.ct & 0x40000)%}
						target="_blank" 
	                {%/if%}
		            class="m">{%$lable_cache%}</a>{%/if%}{%/if%}{%fis_widget_inline%}{%if $showLike == 1%}<span data-nolog class="liketip" id="like_{%$res.urlSign%}"></span>{%/if%}{%/fis_widget_inline%}</font></td></tr></table>{%/fis_widget%}