{%extends 'base.tpl'%} {%block name='content'%}<style >
.op_baike2{ font-size:10pt;}
.op_baike2_clear{clear:both}
.op_baike2 p{ margin:3px 0; padding:0px;}
.op_baike2_editcount{ color:#666; font-family:Arial;}

.op_baike2_noother a{ font-weight:bold;}
.op_baike2_noother a span{color:#e00;}
.op_baike2_noother span.baikelink, 
.op_baike2_other .baikelink{color:#008000; font-family:Arial;}
.op_baike2_other{border-top:2px solid #E8E8E8; margin:5px 0; padding:5px 0; width:520px;}
.op_baike2_other dd{ margin:0px; padding:0px;}
.op_baike2_other dt{ font-weight:bold; width:70px; line-height:22px; float:left; margin:0px; padding:0px;}
.op_baike2_other_list{ width:440px; float:left;}
.op_baike2_other_list a, .op_baike2_other_list span{ margin:0 5px; float:left; *white-space:pre;}
</style>{%$FE_GBVAR.wrapper_prefix%}{%fe_fn_title_prefix%}{%fe_fn_title title="{%$tplData.title%}" url="{%$tplData.url%}"%}{%fe_fn_title_suffix title="{%$tplData.title%}" url="{%$tplData.url%}"%}<div class="op_baike2"><p class="op_baike2_content"> {%$tplData.content|limitlen:140|highlight:0%} <span class="op_baike2_editcount">共{%$tplData.editcount%}次编辑</span> </p> {%if $tplData.link[0]['linkurl']!=""%} <p class="op_baike2_link"> <a target="_blank" href="{%$tplData.link[0]['linkurl']%}">{%$tplData.link[0]['linkcontent']|limitlen:12|highlight:0%}</a> {%if $tplData.link[1]['linkurl']!=""%}&nbsp;-&nbsp;<a target="_blank" href="{%$tplData.link[1]['linkurl']%}">{%$tplData.link[1]['linkcontent']|limitlen:12|highlight:0%}</a>{%/if%} {%if $tplData.link[2]['linkurl']!=""%}&nbsp;-&nbsp;<a target="_blank" href="{%$tplData.link[2]['linkurl']%}">{%$tplData.link[2]['linkcontent']|limitlen:12|highlight:0%}</a>{%/if%} {%if $tplData.link[3]['linkurl']!=""%}&nbsp;-&nbsp;<a target="_blank" href="{%$tplData.link[3]['linkurl']%}">{%$tplData.link[3]['linkcontent']|limitlen:12|highlight:0%}</a>{%/if%} </p> {%/if%} {%if $tplData.other[0]['txt']==""%} <p class="op_baike2_noother"> <span class="baikelink">{%$tplData.showurl%} {%$tplData.date%}</span> </p> {%/if%} {%if $tplData.other[0]['txt']!=""%} <dl class="op_baike2_other"> <dt>其他含义：</dt> <dd class="op_baike2_other_list"> <a href="{%$tplData.other[0]['url']%}" target="_blank">{%$tplData.other[0]['txt']|limitlen:22|highlight:0%}</a> {%if $tplData.other[1]['txt']!=""%}<span>-</span><a href="{%$tplData.other[1]['url']%}" target="_blank">{%$tplData.other[1]['txt']|limitlen:22|highlight:0%}</a> {%/if%} {%if $tplData.other[2]['txt']!=""%}<span>-</span><a href="{%$tplData.other[2]['url']%}" target="_blank">{%$tplData.other[2]['txt']|limitlen:22|highlight:0%}</a> {%/if%} {%if $tplData.other[3]['txt']!=""%}<span>-</span><a href="{%$tplData.other[3]['url']%}" target="_blank">{%$tplData.other[3]['txt']|limitlen:22|highlight:0%}</a> {%/if%} {%if $tplData.other[4]['txt']!=""%}<span>-</span><a href="{%$tplData.other[4]['url']%}" target="_blank">{%$tplData.other[4]['txt']|limitlen:22|highlight:0%}</a> {%/if%} {%if $tplData.other[5]['txt']!=""%} <span>-</span> <a href="{%$tplData.url%}"   target="_blank">查看全部含义&gt;&gt;</a> {%/if%} <br class="op_baike2_clear"> </dd> <dd class="op_baike2_clear baikelink">{%$tplData.showurl%} {%$tplData.date%} {%if $tplData.showlamp!=""%} - <a onmousedown="return c({'fm':'alop','title':this.innerHTML,'url':this.href,'p1':_aMC(this),'p2':jI(this)-1})" target="_blank" href="http://open.baidu.com/" class="op_LAMP">{%$FE_GBVAR.aladdin_txt%}</a>{%/if%}</dd> </dl> {%/if%}</div>{%$FE_GBVAR.wrapper_suffix%}{%/block%}