{%fis_widget%}<li class="bds-list" id="{%$resIndex%}" tpl="se_as_zhidao" mu="{%$res.offsetInfo.url%}"><div class="bds-item-box"><a href="{%get_url token=$res.productType originUrl=$res.offsetInfo.urlEncoded encryptionUrl=$res.encryptionUrl%}" target="_blank" data-click="{
			'F':'{%$res.strategyStr[0]%}',
			'F1':'{%$res.strategyStr[1]%}',
			'F2':'{%$res.strategyStr[2]%}',
			'F3':'{%$res.strategyStr[3]%}',
			'T':'{%$serverTime%}',
			'y':'{%$res.identifyStr%}'}"><h3 class="t">{%$res.offsetInfo.title|limitlen:63|highlight:2%}</h3><div>{%if $res.dispData.ZhidaoReplyNum && $res.dispData.ZhidaoUpdateTime%}<p class="m">{%$res.dispData.ZhidaoReplyNum%}个回答 -{%if $res.dispData.ZhidaoCreateTime%}提问时间:{%$res.dispData.ZhidaoCreateTime|date_format:'%Y年 %m月 %d日'|strip:''%}{%else%}最新回答:{%$res.dispData.ZhidaoUpdateTime%}{%/if%}</p><script>(function(){return ns_c({'fm':'alzd','tab':'zd','is_n_fld':'replynum'});})();</script>{%/if%}{%if $res.dispData.ZhidaoQuestionDescription%}<p><span class="m">问题描述:</span>{%$res.dispData.ZhidaoQuestionDescription|limitlen:138|highlight:2%}</p><script>(function(){return ns_c({'fm':'alzd','tab':'zd','is_n_fld':'description'});})();</script>{%/if%}<p>{%if $res.dispData.ZhidaoBestAnswer%}<span class="m">最佳答案:</span>{%$res.dispData.ZhidaoBestAnswer|limitlen:138|highlight:2%}<script>(function(){return ns_c({'fm':'alzd','tab':'zd','is_n_fld':'bestanswer'});})();</script>{%else%}{%if $res.dispData.ZhidaoNormalAnswer%}{%$res.dispData.ZhidaoNormalAnswer|limitlen:138|highlight:2%}{%else%}{%$res.offsetInfo.summary|limitlen:231|highlight:6%}{%/if%}{%/if%}{%if $res.dispData.ZhidaoBestAnswer%}{%if strlen($res.dispData.ZhidaoBestAnswer)>0%}<br>{%/if%}{%else%}{%if $res.dispData.ZhidaoNormalAnswer%}{%if strlen($res.dispData.ZhidaoNormalAnswer)>0%}<br>{%/if%}{%else%}{%if strlen($res.offsetInfo.summary) > 0%}<br>{%/if%}{%/if%}{%/if%}</p></div></a><span class="g">{%if $res.dispData.DispUrl%}{%$res.dispData.DispUrl|url_bold_html%}{%else%}{%$res.offsetInfo.urlDisplay|url_limit:45:true%}{%/if%}{%display_as_time FactorTimePrecision=$res.dispData.FactorTimePrecision FactorTime=$res.dispData.FactorTime LastModTime=$res.dispData.LastModTime LinkFoundTime=$res.dispData.LinkFoundTime timeShow=$res.timeShow lastModified=$res.offsetInfo.lastModified serverTime=$serverTime%}{%if strlen($res.snapshootKey) > 0%}{%if $res.docType < 0%}-<a data-nolog href="{%$cache_domain%}/c?{%$res.snapshootKey%}&user=baidu&fm=sc&query={%$queryUbs%}&qid={%$queryId%}&p1={%$resIndex%}" 
				{%if !($urlPara.ct & 0x40000)%}
						target="_blank" 
	            {%/if%}
		            class="m">{%$lable_cache%}</a>{%/if%}{%/if%}</span></div></li>{%/fis_widget%}