{%extends 'base.tpl'%} {%block name='content'%}<style>.op_chinajoy{font-family:"宋体";border:1px solid #f5f5f5;width:635px}.op_chinajoy h3{font-size:14px;font-weight:normal;padding-left:9px;height:24px;line-height:24px;color:#000;background:#fdfdfd;border-bottom:1px solid #f5f5f5}.op_chinajoy .op_chinajoy_games{overflow:hidden;zoom:1;padding:10px 0 0}.op_chinajoy .op_chinajoy_item{float:left;width:104px;height:172px;padding:0 0 16px 20px}.op_chinajoy .op_chinajoy_item a{display:block;text-align:center}.op_chinajoy .op_chinajoy_item .img_wrap{p{%*i*%}osition:relative;width:101px;height:141px}.op_chinajoy .op_chinajoy_item .img_wrap img{width:101px;height:141px}.op_chinajoy .op_chinajoy_item .img_border{position:absolute;z-index:10;left:0;top:0;width:99px;height:139px;border:1px solid #000;background:transparent;opacity:.1;filter:alpha(opacity=10)}.op_chinajoy .op_chinajoy_item .game_title{font-size:13px;color:#00c;line-height:13px;padding-top:8px;text-decoration:none}.op_chinajoy .op_chinajoy_pages{display:none;height:20px;padding-bottom:10p{%*i*%}x}.op_chinajoy .op_chinajoy_pages table{border-collapse:collapse;text-align:left;margin:0 auto}.op_chinajoy .op_chinajoy_pages table td{text-align:center}.op_chinajoy .op_chinajoy_pages table td a{border:1px solid #d5d5d5;display:inline-block;outline:0 none;font-family:arial;font-size:11px;font-weight:bold;color:#0064d3;line-height:18px;height:18px;padding:0 5px;text-decoration:none}.op_chinajoy .op_chinajoy_pages table td a b{font-family:"宋体"}.op_chinajoy .op_chinajoy_pages table td a.cur{curso{%*i*%}r:default;color:#000;border:1px solid #fff}.op_chinajoy .op_chinajoy_pages table td a.prev,.op_chinajoy .op_chinajoy_pages table td a.next{font-weight:normal;margin:0 5px}</style>{%$FE_GBVAR.wrapper_prefix%}<div class="op_chinajoy"> <h3>{%$tplData.title%}</h3> <div class="op_chinajoy_games"> </div> <div class="op_chinajoy_pages"> </div></div><script type="text/javascript" >
{%$loop_maxcount=count($tplData.gameitem)%}
var CHINA_JOY_GAME_DATA =[
    {%for $op_loop_count=0 to $loop_maxcount - 2%}
    {
        name: "{%$tplData.gameitem[$op_loop_count]['name']%}",
        provider: "{%$tplData.gameitem[$op_loop_count]['provider']%}",
        url: "{%$tplData.gameitem[$op_loop_count]['url']%}",
        img_url: "{%$tplData.gameitem[$op_loop_count]['img_url']%}"
    },
    {%/for%}
    {%if 0<$loop_maxcount%}
    {
        name: "{%$tplData.gameitem[$loop_maxcount - 1]['name']%}",
        provider: "{%$tplData.gameitem[$loop_maxcount - 1]['provider']%}",
        url: "{%$tplData.gameitem[$loop_maxcount - 1]['url']%}",
        img_url: "{%$tplData.gameitem[$loop_maxcount - 1]['img_url']%}"
    }
    {%/if%}
];
</script><script>A.init(function(){var T = A.baidu;var _this = this;var ChinaJoy = {pn: 10,curIndex: 0,init: function() {this.pl = Math.ceil(CHINA_JOY_GAME_DATA.length / this.pn);this.imgWrap = _this.find('.op_chinajoy_games');this.changeImage(0);if(this.pl > 1) {this.initPages();}},initPages: function() {_this.find('.op_chinajoy_pages').css('display', 'block');var tds = '<table><tbody><tr class="op_chinajoy_pages_tr"><td><a href="javasript:void(0)" class="prev" pageIndex="-1"><b><</b>&nbsp;上一页</a{%*i*%}></td>';for(var i = 0; i < this.pl; i++) {tds += '<td><a href="javasript:void(0)" class="page" pageIndex="' + i + '">' + (i + 1) + '</a></td>';}tds += '<td><a href="javasript:void(0)" class="next" pageIndex="+1">下一页&nbsp;<b>></b></a></td></tr></tbody></table>';_this.find('.op_chinajoy_pages').html(tds);this.tr = _this.find('.op_chinajoy_pages_tr')[0];this.changePage(0);$(this.tr).click(function(e){var clickLink = e.target; var pageIndex = $(clickLink).attr('pageIndex');if('-1' == pageIndex) {Chi{%*i*%}naJoy.curIndex = ChinaJoy.curIndex - 1;}else if('+1' == pageIndex) {ChinaJoy.curIndex = ChinaJoy.curIndex + 1;}else if(!!pageIndex) {ChinaJoy.curIndex = +pageIndex;}if(ChinaJoy.curIndex < 0) {ChinaJoy.curIndex = 0;}if(ChinaJoy.curIndex >= ChinaJoy.pl) {ChinaJoy.curIndex = ChinaJoy.pl - 1;}ChinaJoy.changeImage(ChinaJoy.curIndex);ChinaJoy.changePage(ChinaJoy.curIndex);e.preventDefault();});},changeImage: function(idx) {var pages = _this.find(".op_chinajoy_item_page");pages.each(function(i,page){$({%*i*%}page).css('display', 'none');});var toPage = _this.find(".op_chinajoy_item_page_" + idx);if(toPage[0]) {toPage.css('display', 'block');return;}var imgs = '<div class="op_chinajoy_item_page op_chinajoy_item_page_' + idx + '">';var curImgData;for(var i = idx * this.pn; i < (idx + 1) * this.pn && i < CHINA_JOY_GAME_DATA.length; i++) {curImgData = CHINA_JOY_GAME_DATA[i];imgs += ['<div class="op_chinajoy_item">','<a class="img_wrap" href="' + curImgData['url'] + '" target="_blank">','<span class="img{%*i*%}_border"></span>','<img src="' + curImgData['img_url'] + '" alt="烈火战神" />','</a>','<a class="game_title" title="' + curImgData['provider'] + '" href="' + curImgData['url'] + '" target="_blank">' + curImgData['name'] + '</a>',' </div>'].join('');}this.imgWrap.append(imgs + '</div>');},changePage: function(idx) {if(idx == 0) { $(ChinaJoy.tr).eq(0).find(".prev").css('display', 'none');}else { $(ChinaJoy.tr).eq(0).find(".prev").css('display', 'block');}if(idx == this.pl - 1) { $(ChinaJoy.tr).eq(0).f{%*i*%}ind(".next").css('display', 'none');}else {$(ChinaJoy.tr).eq(0).find(".next").css('display', 'block');}var links = $(ChinaJoy.tr).find(".page");links.each(function(i,link){if (idx == i) {$(link).addClass('cur'); }else { $(link).removeClass('cur');}});}};ChinaJoy.init();});</script>{%$FE_GBVAR.wrapper_suffix%}{%/block%}